application: qmpostoffice
version: 1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- warmup

handlers:
- url: /tasks/.*
  script: mail.py
  login: admin
  
- url: /
  static_dir: static
  login: admin
